trailingComma: es5
tabWidth: 4
bracketSameLine: true
semi: true
singleAttributePerLine: false
quoteProps: 'consistent'
overrides:
  - files: '*.yml'
    options:
      tabWidth: 2
      singleQuote: true
